version: "3.3"
services:
    db:
        container_name: forum-example-db
        image: forum-example-db
        build:
            context: ./db
        volumes:
            - db:/var/lib/postgresql/data
        env_file:
            - ./.env
        networks:
            - network
        ports:
            - 5432:5432

    pgadmin:
        container_name: forum-example-pgadmin
        image: dpage/pgadmin4
        env_file:
            - ./.env
        depends_on:
            - db 
        networks:
            - network
        ports:
            - 5050:5050

    graphql:
        container_name: forum-example-graphql
        image: forum-example-graphql
        build:
            context: ./graphql
        env_file:
            - ./.env
        depends_on:
            - db
        networks:
            - network
        ports:
            - 5433:5433
        command: ["--connection", "${DATABASE_URL}", "--port", "5433", "--schema", "public", "--append-plugins", "postgraphile-plugin-connection-filter"]


networks:
    network:

volumes:
    db: